import { getCookie, removeCookies, setCookies } from "cookies-next";
import jwtDecode from "jwt-decode";
import Head from "next/head";
import { WP_BaseHttp } from "../src/axios/wp";
import Dashboard from "../src/components/Dashboard.page/Dashboard.component";
import Footer from "../src/components/Footer/Footer.component";
import { Header } from "../src/components/Header/Header.components";
import { getCustomerData } from "../src/wp-rest/getCustomerData";
import { getHomepageData } from "../src/wp-rest/getHomepageData.call";
import { getMenuCategoriesData } from "../src/wp-rest/getMenuCategoriesData.call";
import { getOrdersFromUser } from "../src/wp-rest/getOrdersFromUserId.call";

export default function DashboardPage({
  data,
  categoriesLinkList,
  orders,
  customer,
}) {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header data={data} categories={categoriesLinkList} />
      <Dashboard customer={customer} orders={orders} />
      <Footer data={data} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const token = getCookie("accessToken", context);
  const { req, res } = context;

  if (!token) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  const config = {
    headers: { Authorization: `Bearer ${token}` },
  };

  let invalidToken = false;
  let response;

  try {
    response = await WP_BaseHttp.get(
      "wp-json/simple-jwt-login/v1/auth/validate",
      config
    );
  } catch {
    invalidToken = true;
  }

  if (invalidToken) {
    try {
      response = await WP_BaseHttp.post(
        "wp-json/simple-jwt-login/v1/auth/refresh",
        {
          JWT: token,
        }
      );
      removeCookies("accessToken", { req, res });
      setCookies("accessToken", response.data.data.jwt, {
        req,
        res,
        maxAge: 60 * 60 * 24 * 14,
        sameSite: true,
      });
    } catch (err) {
      return {
        redirect: {
          destination: "/signOut",
          permanent: false,
        },
      };
    }
  }

  const user = jwtDecode(token);

  const data = await getHomepageData();
  const categoriesLinkList = await getMenuCategoriesData();
  const orders = await getOrdersFromUser(user);
  const customer = JSON.parse(await getCustomerData(user));

  return {
    props: {
      data,
      categoriesLinkList,
      orders,
      customer,
    }, // will be passed to the page component as props
  };
}
