import axios from "axios";
import { getCookie } from "cookies-next";
import Head from "next/head";
import Footer from "../src/components/Footer/Footer.component";
import { Header } from "../src/components/Header/Header.components";
import { getHomepageData } from "../src/wp-rest/getHomepageData.call";
import { getMenuCategoriesData } from "../src/wp-rest/getMenuCategoriesData.call";

export default function DashboardPage({ data, categoriesLinkList }) {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header data={data} categories={categoriesLinkList} />
      <h1>You are logged in</h1>
      <Footer data={data} />
    </div>
  );
}

export async function getServerSideProps(context) {
  // const res = await fetch(`https://...`);
  // const data = await res.json();

  // if (!data) {
  //   return {
  //     notFound: true,
  //   };
  // }

  const token = getCookie("accessToken", context);
  // console.log(token, { context });

  // if (!token) {
  //   return {
  //     redirect: {
  //       destination: "/",
  //       permanent: false,
  //     },
  //   };
  // }

  // const validationRes = await axios.post("/api/auth/validate", {
  //   accessToken: token,
  // });

  // if (validationRes.status === 400) {
  //   return {
  //     redirect: {
  //       destination: "/",
  //       permanent: false,
  //     },
  //   };
  // }

  const data = await getHomepageData();
  const categoriesLinkList = await getMenuCategoriesData();

  return {
    props: {
      data,
      categoriesLinkList,
    }, // will be passed to the page component as props
  };
}
