import Head from "next/head";
import { Header } from "../src/components/Header/Header.components";
import { getHomepageData } from "../src/wp-rest/getHomepageData.call";
import { getMenuCategoriesData } from "../src/wp-rest/getMenuCategoriesData.call";
import Footer from "../src/components/Footer/Footer.component";
import Favorites from "../src/components/Favorites.page/Favorites.component";

export default function FavoritesPage({ data, categoriesLinkList }) {
  return (
    <div>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header data={data} categories={categoriesLinkList} />

      <Favorites />

      <Footer data={data} />
    </div>
  );
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps() {
  const data = await getHomepageData();
  const categoriesLinkList = await getMenuCategoriesData();

  return {
    props: {
      data,
      categoriesLinkList,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  };
}
