import Head from "next/head";
import { Header } from "../src/components/Header/Header.components";
import HeroHomepage from "../src/components/Homepage/Hero/Hero.component";
import SalesHomepage from "../src/components/Homepage/Sales/Sales.component";
import SectionHomepage from "../src/components/Homepage/Section/Section.component";
import { getHomepageData } from "../src/wp-rest/getHomepageData.call";
import { getMenuCategoriesData } from "../src/wp-rest/getMenuCategoriesData.call";
import { getProductsByCategoryId } from "../src/wp-rest/getProductsByCategoryId.call";

export default function Home({ data, categoriesLinkList, salesProducts }) {
  console.log(salesProducts);
  return (
    <div>
      <Head>
        <title>Brubeck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header data={data} categories={categoriesLinkList} />

      <main>
        <HeroHomepage data={data} />
        <SalesHomepage products={salesProducts} />
        <SectionHomepage data={data} />
      </main>

      <footer>footer</footer>
    </div>
  );
}

// This function gets called at build time on server-side.
// It may be called again, on a serverless function, if
// revalidation is enabled and a new request comes in
export async function getStaticProps() {
  const data = await getHomepageData();
  const categoriesLinkList = await getMenuCategoriesData();
  const salesProducts = await getProductsByCategoryId(33);

  return {
    props: {
      data,
      categoriesLinkList,
      salesProducts,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 10, // In seconds
  };
}
