import Head from "next/head";
import { useRouter } from "next/router";
import { signOutUser } from "../src/redux/user/user.slice";
import { useDispatch } from "react-redux";
import { useEffect } from "react";

export default function SignOutPage() {
  const dispatch = useDispatch();
  const router = useRouter();

  useEffect(() => {
    dispatch(signOutUser());
    router.push("/login");
  }, []);

  return (
    <div>
      <Head>
        <title>Выйти</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Exiting account...
    </div>
  );
}
